// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity of the running backend — surfaced on the home screen so the user
 * (and we, during development) can confirm the IPC bridge is live.
 */
export type AppInfo = { 
/**
 * Product name.
 */
name: string, 
/**
 * Semver of the app (from Cargo).
 */
version: string, 
/**
 * Tauri runtime version backing this build.
 */
tauri_version: string, 
/**
 * Target OS the backend was compiled for (`macos`, `windows`, ...).
 */
platform: string, 
/**
 * CPU architecture (`aarch64`, `x86_64`, ...).
 */
arch: string, 
/**
 * A friendly greeting so the home screen has human-readable proof of life.
 */
greeting: string, };
