// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted audio configuration.
 */
export type AudioSettings = { 
/**
 * Selected input device name, or None to follow the system default.
 */
input_device: string | null, 
/**
 * Selected output device name, or None to follow the system default.
 */
output_device: string | null, 
/**
 * Project/engine sample rate in Hz.
 */
sample_rate: number, 
/**
 * I/O buffer size in frames.
 */
buffer_size: number, };
