// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One audio device (input or output) with the capabilities the UI needs.
 */
export type AudioDevice = { 
/**
 * Human-readable device name as reported by the OS.
 */
name: string, 
/**
 * `"input"` or `"output"`.
 */
direction: string, 
/**
 * Max channel count across the device's supported configs (0 if unknown).
 */
channels: number, 
/**
 * Standard sample rates (Hz) the device supports.
 */
sample_rates: Array<number>, 
/**
 * Whether this is the host's default device for its direction.
 */
is_default: boolean, };
