// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EqBandType } from "./EqBandType";

/**
 * One EQ band's parameters.
 */
export type EqBand = { enabled: boolean, band_type: EqBandType, freq: number, q: number, gain_db: number, };
