// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Band filter shape, mirrored to TS for the band editor.
 */
export type EqBandType = "high_pass" | "low_pass" | "bell" | "low_shelf" | "high_shelf";
