// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chapter to embed in the exported file, as supplied by the renderer
 * (AI-suggested show-notes chapters the user accepted, or manual ones). The
 * backend re-sorts and clamps these into the take before they reach ffmpeg, so
 * an out-of-order or zero-length chapter can never be embedded.
 */
export type ExportChapterInput = { 
/**
 * Chapter start, in milliseconds from the top of the programme.
 */
start_ms: number, 
/**
 * Short chapter title shown by the podcast player.
 */
title: string, };
