// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output container/codec for an export.
 */
export type ExportFormat = "wav" | "mp3" | "aac" | "flac";
