// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";

/**
 * A platform-ready export preset, exposed to the UI picker.
 */
export type ExportPresetInfo = { id: string, label: string, format: ExportFormat, 
/**
 * Encoder bitrate (kbps); `None` for lossless/PCM formats.
 */
bitrate_kbps: number | null, 
/**
 * 1 = mono, 2 = stereo.
 */
channels: number, 
/**
 * The loudness target id to normalise to (see `LoudnessTarget`).
 */
target_id: string, description: string, 
/**
 * True when writing this format needs the ffmpeg sidecar (not WAV).
 */
requires_encoder: boolean, };
