// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";
import type { NormalizationReport } from "./NormalizationReport";

/**
 * The outcome of an export render, returned to the UI.
 */
export type ExportResult = { 
/**
 * Absolute path of the file written.
 */
output_path: string, 
/**
 * The format actually written (WAV today, even for encoder presets).
 */
written_format: ExportFormat, 
/**
 * The export preset the user picked.
 */
requested_preset_id: string, 
/**
 * File size in bytes.
 */
bytes: number, 
/**
 * Programme duration in milliseconds.
 */
duration_ms: number, channels: number, sample_rate: number, 
/**
 * Before/after loudness measurement of the bounce.
 */
loudness: NormalizationReport, 
/**
 * True when the achieved integrated loudness is within 0.5 LU of target
 * (the plan's verification threshold).
 */
target_reached: boolean, 
/**
 * Human-readable caveat (encoder pending, or loudness off target).
 */
note: string | null, };
