// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The curve a fade ramp follows from silence (0.0) to unity (1.0).
 */
export type FadeShape = "linear" | "equal_power";
