// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated request to import a recording into a project, parsed from a
 * `sundaystudio://import?…` deep link. The renderer turns this into a real
 * take/project via the normal import flow.
 */
export type ImportRequest = { 
/**
 * Absolute path to the source audio/video file. Always present.
 */
path: string, 
/**
 * Scheme of the app that launched us, so we can hand a result back later
 * (e.g. `"sundayrec"`). `None` for a plain user-initiated link.
 */
return_to: string | null, };
