/**
 * Type bindings auto-generated by `ts-rs` from Rust types. Do not edit the
 * individual `*.ts` files by hand — they are regenerated by
 * `cargo test export_bindings` (run from `src-tauri/`).
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { AppInfo, AudioDeviceList } from "@/lib/bindings";
 */

export type { AppInfo } from "./AppInfo";
export type { AudioDevice } from "./AudioDevice";
export type { AudioDeviceList } from "./AudioDeviceList";
export type { ToneResult } from "./ToneResult";
export type { AudioSettings } from "./AudioSettings";
export type { LatencyEstimate } from "./LatencyEstimate";
export type { LatencyZone } from "./LatencyZone";
export type { Project } from "./Project";
export type { Track } from "./Track";
export type { Take } from "./Take";
export type { Region } from "./Region";
export type { Marker } from "./Marker";
export type { ProjectSnapshot } from "./ProjectSnapshot";
export type { RecentProject } from "./RecentProject";

/** Error shape returned by every Tauri command (see error.rs).
 *  Keep this union in sync with `AppError::code()` in Rust. */
export interface AppError {
  code: "not_found" | "validation" | "audio" | "io" | "json" | "internal";
  message: string;
}
