/**
 * Type bindings auto-generated by `ts-rs` from Rust types. Do not edit the
 * individual `*.ts` files by hand — they are regenerated by
 * `cargo test export_bindings` (run from `src-tauri/`).
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { AppInfo, AudioDeviceList } from "@/lib/bindings";
 */

export type { AppInfo } from "./AppInfo";
export type { AudioDevice } from "./AudioDevice";
export type { AudioDeviceList } from "./AudioDeviceList";
export type { ToneResult } from "./ToneResult";
export type { AudioSettings } from "./AudioSettings";
export type { LatencyEstimate } from "./LatencyEstimate";
export type { LatencyZone } from "./LatencyZone";
export type { Project } from "./Project";
export type { ProjectMeta } from "./ProjectMeta";
export type { Track } from "./Track";
export type { Take } from "./Take";
export type { Region } from "./Region";
export type { Marker } from "./Marker";
export type { ProjectSnapshot } from "./ProjectSnapshot";
export type { TimelineSnapshot } from "./TimelineSnapshot";
export type { WaveformPeaks } from "./WaveformPeaks";
export type { SilenceSpan } from "./SilenceSpan";
export type { RecentProject } from "./RecentProject";
export type { TemplateInfo } from "./TemplateInfo";
export type { TemplateTrackInfo } from "./TemplateTrackInfo";
export type { PresetInfo } from "./PresetInfo";
export type { EqBand } from "./EqBand";
export type { EqBandType } from "./EqBandType";
export type { LoudnessMeasurement } from "./LoudnessMeasurement";
export type { LoudnessTarget } from "./LoudnessTarget";
export type { NormalizationReport } from "./NormalizationReport";
export type { MasterPresetInfo } from "./MasterPresetInfo";
export type { ExportFormat } from "./ExportFormat";
export type { ExportPresetInfo } from "./ExportPresetInfo";
export type { ExportResult } from "./ExportResult";
export type { FadeShape } from "./FadeShape";
export type { ImportRequest } from "./ImportRequest";
export type { LevelingTrack } from "./LevelingTrack";
export type { LevelingSnapshot } from "./LevelingSnapshot";
export type { LevelingSuggestion } from "./LevelingSuggestion";
export type { LevelingResult } from "./LevelingResult";

/** Error shape returned by every Tauri command (see error.rs).
 *  Keep this union in sync with `AppError::code()` in Rust. */
export interface AppError {
  code: "not_found" | "validation" | "audio" | "database" | "io" | "json" | "internal";
  message: string;
}
