// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the user fills out to describe the jingle they want.
 *
 * Field-for-field the same as the `JingleSpec` interface in
 * `src/lib/jingle.ts`; the form already builds this object, and the command
 * receives it verbatim.
 */
export type JingleSpec = { title: string, duration_sec: number, mood: string, tempo_bpm: number, instruments: Array<string>, voiceover_text: string | null, };
