// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The finished jingle, returned to the renderer.
 *
 * `audio_url` points at the generated music the wrapper produced (the client
 * downloads it into the project's `jingles/stems/` folder, then the offline
 * render plan in `src/lib/jingle.ts` mixes it with any voiceover). The metadata
 * lets the UI label "Generated by Suno · 30s · 120 BPM".
 */
export type JingleResult = { 
/**
 * URL of the generated audio the client downloads.
 */
audio_url: string, 
/**
 * The model / provider that produced it (echoed for the UI label).
 */
model: string, 
/**
 * Duration the provider actually rendered, in seconds (may differ slightly
 * from the request; the offline render plan trims to the exact target).
 */
duration_sec: number, 
/**
 * The title the jingle was generated under (echoes the spec).
 */
title: string, 
/**
 * Optional cover-art / thumbnail URL the provider returned, if any.
 */
image_url: string | null, };
