// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latency zone for UI colour-coding (plan 1.3: green < 10ms, yellow 10–20,
 * red > 20).
 */
export type LatencyZone = "green" | "yellow" | "red";
