// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatencyZone } from "./LatencyZone";

/**
 * Estimated round-trip monitoring latency for a sample-rate / buffer choice.
 */
export type LatencyEstimate = { 
/**
 * Round-trip estimate in milliseconds.
 */
ms: number, zone: LatencyZone, };
