// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One track's current state, fed to the model. Loudness is optional because a
 * freshly-imported or empty track may not have been measured yet.
 */
export type LevelingTrack = { 
/**
 * Stable track id (echoed back so we can map a suggestion to its track).
 */
track_id: string, 
/**
 * Display name — the model leans on this for its human reason ("Guest mic").
 */
name: string, 
/**
 * The track's current fader gain in dB.
 */
current_gain_db: number, 
/**
 * Integrated loudness in LUFS, if measured (lower = quieter).
 */
integrated_lufs: number | null, 
/**
 * True-peak in dBTP, if measured (near 0 = at risk of clipping).
 */
true_peak_dbtp: number | null, 
/**
 * How many clips this track holds on the timeline (0 = empty track).
 */
clip_count: number, };
