// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LevelingTrack } from "./LevelingTrack";

/**
 * The whole project's leveling input — the tracks plus the loudness target the
 * final mix is aiming for, so the model can level *toward* the platform goal.
 */
export type LevelingSnapshot = { tracks: Array<LevelingTrack>, 
/**
 * The integrated-LUFS goal of the chosen platform target (e.g. -16 for
 * Spotify), so suggestions push the mix the right direction.
 */
target_lufs: number, };
