// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LevelingSuggestion } from "./LevelingSuggestion";

/**
 * The full result returned to the renderer: the suggestions plus the model that
 * produced them (so the UI can label "Suggested by Claude").
 */
export type LevelingResult = { suggestions: Array<LevelingSuggestion>, model: string, };
