// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-track suggestion the model returns.
 */
export type LevelingSuggestion = { 
/**
 * Which track this applies to (matches a [`LevelingTrack::track_id`]).
 */
track_id: string, 
/**
 * The suggested new fader gain in dB (absolute, not a delta) — already
 * clamped to a safe range relative to the track's current gain.
 */
suggested_gain_db: number, 
/**
 * A short, human reason the UI shows next to the chip.
 */
reason: string, };
