// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A loudness snapshot. Every field is `None` when undefined (silence, or a
 * window that hasn't filled yet) so it crosses IPC as `number | null`.
 */
export type LoudnessMeasurement = { 
/**
 * Integrated (gated, whole-program) loudness — the platform target metric.
 */
integrated_lufs: number | null, 
/**
 * Short-term loudness over the trailing 3 seconds.
 */
short_term_lufs: number | null, 
/**
 * Momentary loudness over the trailing 400 ms.
 */
momentary_lufs: number | null, 
/**
 * Loudness range (LRA) in LU — the program's macro-dynamics.
 */
loudness_range_lu: number | null, 
/**
 * True (inter-sample) peak in dBTP, across all channels.
 */
true_peak_dbtp: number | null, 
/**
 * Sample peak in dBFS, across all channels.
 */
sample_peak_dbfs: number | null, };
