// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A platform's normalisation target: an integrated-loudness goal and the true-
 * peak ceiling it expects you to stay under.
 */
export type LoudnessTarget = { id: string, label: string, 
/**
 * Target integrated loudness (LUFS). Negative.
 */
integrated_lufs: number, 
/**
 * Maximum allowed true peak (dBTP). Negative.
 */
true_peak_ceiling_dbtp: number, description: string, };
