// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timeline marker (also used as a podcast chapter on export).
 */
export type Marker = { id: string, project_id: string, position_ms: number, label: string, color: string, };
