// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mastering-preset metadata for the UI picker.
 */
export type MasterPresetInfo = { id: string, label: string, description: string, 
/**
 * The loudness target id this preset normalises to (see `LoudnessTarget`).
 */
target_id: string, };
