// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoudnessMeasurement } from "./LoudnessMeasurement";

/**
 * The result of a normalisation pass: how much gain we applied, the before/
 * after measurements, and whether we could hit the target without clipping.
 */
export type NormalizationReport = { target_lufs: number, gain_applied_db: number, before: LoudnessMeasurement, after: LoudnessMeasurement, 
/**
 * True when the target loudness was unreachable without exceeding the true-
 * peak ceiling, so gain was capped to stay clip-safe. A brick-wall limiter
 * (Phase 4.2b) is what lets you push past this honestly.
 */
gain_capped_by_peak: boolean, 
/**
 * True when the achieved integrated loudness is within 0.5 LU of target.
 */
reached_target: boolean, };
