// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The player's transport state — what the UI polls to draw the playhead and
 * transport buttons.
 */
export type PlaybackStatus = { 
/**
 * Whether the transport is rolling.
 */
playing: boolean, 
/**
 * Playhead position in milliseconds.
 */
position_ms: number, 
/**
 * Total timeline length in milliseconds.
 */
length_ms: number, };
