// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preset metadata for the UI (the preset picker).
 */
export type PresetInfo = { id: string, label: string, description: string, };
