// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the app-level project registry.
 */
export type ProjectMeta = { 
/**
 * Stable identifier (UUIDv4, not the per-project UUID stored in SQLite).
 */
id: string, 
/**
 * Human-readable project name (mirrors `Project.name`).
 */
name: string, 
/**
 * Absolute path to the `.scast` folder.
 */
path: string, 
/**
 * Epoch ms the project was created.
 */
created_at: number, 
/**
 * Epoch ms the registry entry was last modified (rename / save).
 */
updated_at: number, };
