// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Marker } from "./Marker";
import type { Project } from "./Project";
import type { Track } from "./Track";

/**
 * A project plus its tracks and markers — what `project_open` returns so the
 * UI can render the whole project in one round-trip.
 */
export type ProjectSnapshot = { project: Project, tracks: Array<Track>, markers: Array<Marker>, };
