// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recording project. One project per `.sqlite` file.
 */
export type Project = { id: string, name: string, sample_rate: number, channel_count: number, 
/**
 * Epoch milliseconds (kept as f64 so TS sees a plain number).
 */
created_at: number, };
