// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A recent-projects entry (stored app-side, see `scast`).
 */
export type RecentProject = { name: string, 
/**
 * Absolute path to the `.scast` folder.
 */
path: string, 
/**
 * Epoch milliseconds the project was last opened.
 */
last_opened: number, };
