// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI polls while the transport is wired: whether a take is rolling,
 * the live captured-frame count (→ duration) and overruns, plus the per-channel
 * peak meters in dBFS (one entry per captured channel).
 */
export type RecordingStatus = { 
/**
 * Whether a take is currently being captured.
 */
recording: boolean, 
/**
 * Frames captured so far (one per per-channel sample); 0 when idle.
 */
captured_frames: number, 
/**
 * Captured duration in milliseconds, derived from `captured_frames`.
 */
duration_ms: number, 
/**
 * Samples dropped to ring overruns so far (0 is healthy).
 */
dropped: number, 
/**
 * Per-channel peak in dBFS since the last poll (UI meters). Empty when idle.
 */
meters_dbfs: Array<number>, };
