// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-destructive reference to a time range within a take, placed on the
 * timeline of a target track.
 */
export type Region = { id: string, take_id: string, source_track_id: string, target_track_id: string, start_in_take_ms: number, end_in_take_ms: number, position_in_timeline_ms: number, fade_in_ms: number, fade_out_ms: number, gain_adjust_db: number, };
