// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the show-notes call needs: the transcript and a little context.
 *
 * `duration_ms` lets us clamp every returned timestamp into the real take, so
 * the model can never place a chapter or clip past the end of the audio.
 */
export type ShowNotesInput = { 
/**
 * The full transcript text. Plain text or lightly-timestamped captions; the
 * model reads it as prose and infers chapter boundaries.
 */
transcript: string, 
/**
 * Total programme length in milliseconds, used to clamp timestamps. `0`
 * disables clamping (we then only enforce ordering and non-negativity).
 */
duration_ms: number, 
/**
 * Free-text priming carried from the deep link (e.g. "Sermon, speaker:
 * Ola"), or typed by the user. Helps the model name chapters sensibly.
 */
context: string | null, 
/**
 * Glossary terms (speaker names, ministry jargon) so the model spells them
 * right in titles and chapter names. De-duplicated upstream by the deep-link
 * parser; passed through verbatim here.
 */
glossary: Array<string>, };
