// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One suggested social/highlight clip: an in/out span plus why it's worth
 * clipping. The UI shows these as cards; the user picks which to export.
 */
export type ShowNotesClip = { 
/**
 * Clip start, in milliseconds.
 */
start_ms: number, 
/**
 * Clip end, in milliseconds (always strictly after `start_ms`).
 */
end_ms: number, 
/**
 * A short reason the clip is compelling ("Strong, quotable summary line").
 */
reason: string, };
