// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShowNotesChapter } from "./ShowNotesChapter";
import type { ShowNotesClip } from "./ShowNotesClip";

/**
 * The full show-notes result returned to the renderer.
 *
 * Everything here has already been sanitized by [`parse_response`]: titles are
 * trimmed and bounded, chapters are ordered and clamped into the take, clips are
 * valid spans, and the model that produced it is echoed for the "Suggested by
 * Claude" label.
 */
export type ShowNotes = { 
/**
 * A few episode title options for the user to pick from.
 */
title_options: Array<string>, 
/**
 * Norwegian episode summary (Norwegian-first, per Sunday house style).
 */
summary_no: string, 
/**
 * English episode summary.
 */
summary_en: string, 
/**
 * Timestamped chapters, ordered by `start_ms`.
 */
chapters: Array<ShowNotesChapter>, 
/**
 * Topic tags for the podcast platforms.
 */
tags: Array<string>, 
/**
 * Suggested highlight/social clips (3–5 when the audio supports it).
 */
clips: Array<ShowNotesClip>, 
/**
 * The model that produced this (for the UI label).
 */
model: string, };
