// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One timestamped chapter. `start_ms` is where the chapter begins on the
 * timeline; the title is what the podcast player shows. These map directly to
 * ffmpeg chapter metadata on export.
 */
export type ShowNotesChapter = { 
/**
 * Chapter start, in milliseconds from the top of the programme.
 */
start_ms: number, 
/**
 * Short, human chapter title (e.g. "Welcome & notices").
 */
title: string, };
