// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A silent span within a take's audio, in milliseconds (take-relative).
 */
export type SilenceSpan = { start_ms: number, end_ms: number, };
