// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A raw recording pass. The WAVs live at `takes/{id}/{source_track}.wav`.
 */
export type Take = { id: string, project_id: string, started_at: number, duration_ms: number, 
/**
 * Track ids captured in this take.
 */
source_tracks: Array<string>, };
