// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateTrackInfo = { name: string, color: string, 
/**
 * 1-based interface input channel, or null for a music/bed track.
 */
input_assignment: number | null, };
