// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateTrackInfo } from "./TemplateTrackInfo";

export type TemplateInfo = { id: string, label: string, description: string, channel_count: number, 
/**
 * How many of the tracks are mics (drives the "N mics" badge).
 */
mic_count: number, tracks: Array<TemplateTrackInfo>, };
