// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Region } from "./Region";
import type { Take } from "./Take";

/**
 * A project's takes and the regions placed from them — what `project_timeline`
 * returns so the editor can render the whole timeline in one round-trip. Tracks
 * and markers already come from [`ProjectSnapshot`].
 */
export type TimelineSnapshot = { takes: Array<Take>, regions: Array<Region>, };
