// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `write_test_tone` produced — surfaced to the UI as proof of life.
 */
export type ToneResult = { 
/**
 * Absolute path to the written WAV file.
 */
path: string, 
/**
 * Sample rate the tone was written at (Hz).
 */
sample_rate: number, 
/**
 * Tone frequency (Hz).
 */
frequency: number, 
/**
 * Duration in milliseconds.
 */
duration_ms: number, 
/**
 * Final file size in bytes.
 */
bytes: bigint, };
