// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mixer/timeline track.
 */
export type Track = { id: string, project_id: string, name: string, color: string, 
/**
 * Interface input channel this track records from (None = unassigned).
 */
input_assignment: number | null, output_assignment: number | null, gain_db: number, 
/**
 * -1.0 (hard left) .. +1.0 (hard right).
 */
pan: number, mute: boolean, solo: boolean, armed: boolean, 
/**
 * Order within the project's track list.
 */
position: number, 
/**
 * Voice-processing preset id (dsp::chain::Preset), or None for no processing.
 * Applied per track at export time.
 */
voice_preset: string | null, };
