// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A take track's precomputed waveform overview.
 */
export type WaveformPeaks = { take_id: string, source_track_id: string, sample_rate: number, duration_ms: number, 
/**
 * Audio samples summarised by each entry in `peaks`.
 */
samples_per_peak: number, 
/**
 * Normalised peak magnitudes 0..1, one per bucket of `samples_per_peak`.
 */
peaks: Array<number>, };
