//! AI jingle generation (Phase 6, Pro) — the product's headline "wow" feature.
//!
//! A user fills out a [`JingleSpec`] (title, duration, mood, tempo, instruments,
//! optional voiceover) and we ask a music-generation model (Suno) for a finished
//! jingle. We never talk to Suno directly from the client: the key would leak.
//! Instead we POST the spec to a small **Edge Function wrapper** (its URL comes
//! from `SUNO_PROXY_URL`) that holds the vendor key, calls Suno, and returns a
//! normalised `{ audio_url, ... }` JSON. Swapping Suno for another vendor is then
//! a server-side change — the client only knows our wrapper's contract, which is
//! exactly the "wrap the abstraction, not the vendor" rule from CLAUDE.md.
//!
//! Mirrors the proven [`super::leveling`] pattern so the whole flow is unit-
//! tested without the network:
//! - [`validate_spec`] rejects nonsense specs before we spend a generation.
//! - [`build_request_body`] turns a spec into the wrapper's request JSON.
//! - [`parse_response`] reads the wrapper's reply into a [`JingleResult`].
//! - [`generate_jingle`] wires the three around an [`HttpTransport`], so a test
//!   drives the whole flow with a canned response and no key / no network.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use super::HttpTransport;

/// Allowed jingle durations in seconds — mirrors `VALID_DURATIONS` in the
/// offline TS layer (`src/lib/jingle.ts`). We keep the two in lockstep so the
/// form and the backend agree on what's renderable.
pub const VALID_DURATIONS: [u32; 3] = [20, 30, 60];

/// Allowed moods — mirrors `VALID_MOODS` in `src/lib/jingle.ts`.
pub const VALID_MOODS: [&str; 4] = ["energetic", "calm", "worshipful", "professional"];

/// Tempo bounds (BPM), mirroring `MIN_BPM`/`MAX_BPM` in `src/lib/jingle.ts`.
pub const MIN_BPM: u32 = 60;
pub const MAX_BPM: u32 = 200;

/// Maximum instrument stems, mirroring `MAX_INSTRUMENTS` in `src/lib/jingle.ts`.
pub const MAX_INSTRUMENTS: usize = 8;

/// The environment variable holding the Edge Function wrapper URL. `None` (the
/// common case in the default gate and for Free-tier / unconfigured installs)
/// means the jingle path is unavailable and the command returns a clean
/// validation error rather than calling out.
pub fn suno_proxy_url() -> Option<String> {
    std::env::var("SUNO_PROXY_URL")
        .ok()
        .filter(|u| !u.trim().is_empty())
}

/// Everything the user fills out to describe the jingle they want.
///
/// The canonical frontend type is the hand-written `JingleSpec` interface in
/// `src/lib/jingle.ts`, which uses richer literal-union field types
/// (`JingleDuration`/`JingleMood`) than ts-rs can express from these plain
/// scalars. To avoid shipping a weaker shadow binding that nothing imports,
/// this struct is intentionally NOT exported via `#[ts(export)]`; the `TS`
/// derive is kept only so it composes if a future exported type embeds it.
/// The form builds the TS spec and the command receives it verbatim.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
pub struct JingleSpec {
    pub title: String,
    pub duration_sec: u32,
    pub mood: String,
    pub tempo_bpm: u32,
    pub instruments: Vec<String>,
    #[serde(default)]
    pub voiceover_text: Option<String>,
}

/// The finished jingle, returned to the renderer.
///
/// `audio_url` points at the generated music the wrapper produced (the client
/// downloads it into the project's `jingles/stems/` folder, then the offline
/// render plan in `src/lib/jingle.ts` mixes it with any voiceover). The metadata
/// lets the UI label "Generated by Suno · 30s · 120 BPM".
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../src/lib/bindings/JingleResult.ts")]
pub struct JingleResult {
    /// URL of the generated audio the client downloads.
    pub audio_url: String,
    /// The model / provider that produced it (echoed for the UI label).
    pub model: String,
    /// Duration the provider actually rendered, in seconds (may differ slightly
    /// from the request; the offline render plan trims to the exact target).
    pub duration_sec: u32,
    /// The title the jingle was generated under (echoes the spec).
    pub title: String,
    /// Optional cover-art / thumbnail URL the provider returned, if any.
    #[serde(default)]
    pub image_url: Option<String>,
}

/// One field-level validation problem with a spec.
#[derive(Debug, Clone, PartialEq)]
pub struct SpecError {
    pub field: &'static str,
    pub message: String,
}

/// Validate a [`JingleSpec`], returning every field-level problem.
///
/// Pure mirror of `validateJingleSpec` in `src/lib/jingle.ts` — the backend
/// re-checks rather than trusting the form, so a malformed IPC payload (or a
/// future caller) can never spend a generation on garbage.
pub fn validate_spec(spec: &JingleSpec) -> Vec<SpecError> {
    let mut errors = Vec::new();

    if spec.title.trim().is_empty() {
        errors.push(SpecError {
            field: "title",
            message: "Title is required.".into(),
        });
    }

    if !VALID_DURATIONS.contains(&spec.duration_sec) {
        errors.push(SpecError {
            field: "duration_sec",
            message: format!(
                "Duration must be one of {} seconds.",
                VALID_DURATIONS
                    .iter()
                    .map(|d| d.to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        });
    }

    if !VALID_MOODS.contains(&spec.mood.as_str()) {
        errors.push(SpecError {
            field: "mood",
            message: format!("Mood must be one of: {}.", VALID_MOODS.join(", ")),
        });
    }

    if spec.tempo_bpm < MIN_BPM || spec.tempo_bpm > MAX_BPM {
        errors.push(SpecError {
            field: "tempo_bpm",
            message: format!("BPM must be between {MIN_BPM} and {MAX_BPM}."),
        });
    }

    let instruments: Vec<&String> = spec
        .instruments
        .iter()
        .filter(|i| !i.trim().is_empty())
        .collect();
    if instruments.is_empty() {
        errors.push(SpecError {
            field: "instruments",
            message: "At least one instrument stem is required.".into(),
        });
    } else if instruments.len() > MAX_INSTRUMENTS {
        errors.push(SpecError {
            field: "instruments.length",
            message: format!("Maximum {MAX_INSTRUMENTS} instrument stems allowed."),
        });
    }

    errors
}

/// Build a human-readable prompt describing the jingle for the music model.
///
/// Separate from [`build_request_body`] so the wording is testable on its own.
pub fn build_prompt(spec: &JingleSpec) -> String {
    let instruments = spec
        .instruments
        .iter()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "A {mood}, {bpm} BPM instrumental jingle for a church podcast titled \
         \"{title}\". Featured instruments: {instruments}. About {dur} seconds, \
         clean intro and a strong, memorable hook. No vocals.",
        mood = spec.mood,
        bpm = spec.tempo_bpm,
        title = spec.title.trim(),
        instruments = instruments,
        dur = spec.duration_sec,
    )
}

/// Build the request body POSTed to the Edge Function wrapper.
///
/// The wrapper's contract is deliberately small and provider-agnostic: a prompt,
/// the structured spec fields it may forward to Suno, and `instrumental: true`
/// so the generated bed has no vocals (our voiceover is added later, offline).
pub fn build_request_body(spec: &JingleSpec) -> serde_json::Value {
    serde_json::json!({
        "prompt": build_prompt(spec),
        "title": spec.title.trim(),
        "duration_sec": spec.duration_sec,
        "mood": spec.mood,
        "tempo_bpm": spec.tempo_bpm,
        "instruments": spec.instruments,
        "instrumental": true,
    })
}

/// The wrapper's reply shape. The Edge Function normalises whatever Suno returns
/// into this stable envelope, so the client never parses vendor-specific JSON.
#[derive(Deserialize)]
struct ProxyResponse {
    audio_url: String,
    #[serde(default)]
    model: Option<String>,
    #[serde(default)]
    duration_sec: Option<u32>,
    #[serde(default)]
    title: Option<String>,
    #[serde(default)]
    image_url: Option<String>,
}

/// Parse the Edge Function wrapper's response into a [`JingleResult`].
///
/// Robust by construction:
/// - requires a non-empty `audio_url` (a generation with no audio is an error);
/// - fills `title`/`duration_sec` from the spec when the wrapper omits them, so
///   the UI always has something to label the jingle with;
/// - defaults `model` to "suno" when the wrapper doesn't say.
pub fn parse_response(body: &str, spec: &JingleSpec) -> Result<JingleResult, String> {
    let resp: ProxyResponse =
        serde_json::from_str(body).map_err(|e| format!("decoding jingle wrapper reply: {e}"))?;

    if resp.audio_url.trim().is_empty() {
        return Err("jingle wrapper returned an empty audio_url".to_string());
    }

    Ok(JingleResult {
        audio_url: resp.audio_url,
        model: resp
            .model
            .filter(|m| !m.is_empty())
            .unwrap_or_else(|| "suno".to_string()),
        duration_sec: resp.duration_sec.unwrap_or(spec.duration_sec),
        title: resp
            .title
            .filter(|t| !t.is_empty())
            .unwrap_or_else(|| spec.title.trim().to_string()),
        image_url: resp.image_url.filter(|u| !u.is_empty()),
    })
}

/// The complete jingle-generation call: validate the spec, build the request,
/// send it through `transport` to the wrapper at `proxy_url`, and parse the reply
/// into a [`JingleResult`].
///
/// `transport` is the seam: production passes a [`super::ReqwestTransport`],
/// tests pass a mock. A non-2xx HTTP status surfaces the wrapper's error body so
/// the UI can show "generation failed" with the reason.
pub fn generate_jingle(
    transport: &dyn HttpTransport,
    proxy_url: &str,
    spec: &JingleSpec,
) -> Result<JingleResult, String> {
    let errors = validate_spec(spec);
    if !errors.is_empty() {
        let joined = errors
            .iter()
            .map(|e| format!("{}: {}", e.field, e.message))
            .collect::<Vec<_>>()
            .join("; ");
        return Err(format!("invalid jingle spec — {joined}"));
    }

    let body = build_request_body(spec).to_string();
    // The wrapper authenticates the caller itself (session token / its own
    // scheme); the request carries no vendor key. Content-Type is set by the
    // transport.
    let (status, resp_body) = transport.post_json(proxy_url, &[], &body)?;
    if !(200..300).contains(&status) {
        return Err(format!(
            "jingle wrapper returned HTTP {status}: {resp_body}"
        ));
    }

    parse_response(&resp_body, spec)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::RefCell;

    fn good_spec() -> JingleSpec {
        JingleSpec {
            title: "Sunday Recap".into(),
            duration_sec: 30,
            mood: "professional".into(),
            tempo_bpm: 120,
            instruments: vec!["piano".into(), "strings".into()],
            voiceover_text: None,
        }
    }

    /// A canned wrapper reply.
    fn proxy_envelope(audio_url: &str) -> String {
        serde_json::json!({
            "audio_url": audio_url,
            "model": "suno-v4",
            "duration_sec": 30,
            "title": "Sunday Recap",
            "image_url": "https://cdn.example.com/cover.png"
        })
        .to_string()
    }

    struct SeenRequest {
        url: String,
        body: String,
    }

    /// Mock transport: returns a fixed `(status, body)` and records the request.
    struct MockTransport {
        status: u16,
        body: String,
        seen: RefCell<Option<SeenRequest>>,
    }

    impl MockTransport {
        fn ok(body: String) -> Self {
            Self {
                status: 200,
                body,
                seen: RefCell::new(None),
            }
        }
    }

    impl HttpTransport for MockTransport {
        fn post_json(
            &self,
            url: &str,
            _headers: &[(&str, &str)],
            body: &str,
        ) -> Result<(u16, String), String> {
            *self.seen.borrow_mut() = Some(SeenRequest {
                url: url.to_string(),
                body: body.to_string(),
            });
            Ok((self.status, self.body.clone()))
        }
    }

    #[test]
    fn validates_a_reasonable_spec() {
        assert!(validate_spec(&good_spec()).is_empty());
    }

    #[test]
    fn rejects_blank_title() {
        let mut spec = good_spec();
        spec.title = "   ".into();
        let errors = validate_spec(&spec);
        assert!(errors.iter().any(|e| e.field == "title"));
    }

    #[test]
    fn rejects_bad_duration_mood_and_tempo() {
        let mut spec = good_spec();
        spec.duration_sec = 45; // not in VALID_DURATIONS
        spec.mood = "spooky".into(); // not a valid mood
        spec.tempo_bpm = 5; // below MIN_BPM
        let errors = validate_spec(&spec);
        assert!(errors.iter().any(|e| e.field == "duration_sec"));
        assert!(errors.iter().any(|e| e.field == "mood"));
        assert!(errors.iter().any(|e| e.field == "tempo_bpm"));
    }

    #[test]
    fn rejects_empty_and_overfull_instrument_lists() {
        let mut empty = good_spec();
        empty.instruments = vec!["   ".into()]; // only blanks → empty after trim
        assert!(validate_spec(&empty)
            .iter()
            .any(|e| e.field == "instruments"));

        let mut too_many = good_spec();
        too_many.instruments = (0..MAX_INSTRUMENTS + 1)
            .map(|i| format!("inst{i}"))
            .collect();
        assert!(validate_spec(&too_many)
            .iter()
            .any(|e| e.field == "instruments.length"));
    }

    #[test]
    fn request_body_carries_the_spec_fields_and_is_instrumental() {
        let spec = good_spec();
        let body = build_request_body(&spec);
        assert_eq!(body["instrumental"], serde_json::json!(true));
        assert_eq!(body["duration_sec"], serde_json::json!(30));
        assert_eq!(body["tempo_bpm"], serde_json::json!(120));
        assert_eq!(body["title"], serde_json::json!("Sunday Recap"));
        let prompt = body["prompt"].as_str().unwrap();
        assert!(prompt.contains("professional"));
        assert!(prompt.contains("piano"));
        assert!(prompt.contains("120 BPM"));
    }

    #[test]
    fn parses_a_known_wrapper_reply() {
        let spec = good_spec();
        let result =
            parse_response(&proxy_envelope("https://cdn.example.com/jingle.mp3"), &spec).unwrap();
        assert_eq!(result.audio_url, "https://cdn.example.com/jingle.mp3");
        assert_eq!(result.model, "suno-v4");
        assert_eq!(result.duration_sec, 30);
        assert_eq!(result.title, "Sunday Recap");
        assert_eq!(
            result.image_url.as_deref(),
            Some("https://cdn.example.com/cover.png")
        );
    }

    #[test]
    fn parse_fills_defaults_when_wrapper_is_terse() {
        let spec = good_spec();
        // Only the required audio_url; everything else falls back.
        let body = serde_json::json!({ "audio_url": "https://x/a.mp3" }).to_string();
        let result = parse_response(&body, &spec).unwrap();
        assert_eq!(result.model, "suno");
        assert_eq!(result.duration_sec, spec.duration_sec);
        assert_eq!(result.title, "Sunday Recap");
        assert!(result.image_url.is_none());
    }

    #[test]
    fn parse_rejects_an_empty_audio_url() {
        let spec = good_spec();
        let body = serde_json::json!({ "audio_url": "" }).to_string();
        assert!(parse_response(&body, &spec).is_err());
    }

    #[test]
    fn generate_drives_the_whole_flow_with_a_mock() {
        let spec = good_spec();
        let transport = MockTransport::ok(proxy_envelope("https://cdn.example.com/jingle.mp3"));

        let result =
            generate_jingle(&transport, "https://proxy.example.com/jingle", &spec).unwrap();
        assert_eq!(result.audio_url, "https://cdn.example.com/jingle.mp3");

        // The request went to the wrapper URL and carried the spec.
        let seen = transport.seen.borrow();
        let req = seen.as_ref().unwrap();
        assert_eq!(req.url, "https://proxy.example.com/jingle");
        assert!(req.body.contains("Sunday Recap"));
        assert!(req.body.contains("instrumental"));
    }

    #[test]
    fn generate_rejects_an_invalid_spec_before_calling_out() {
        let mut spec = good_spec();
        spec.title = "".into();
        spec.tempo_bpm = 9999;
        let transport = MockTransport::ok(proxy_envelope("https://x/a.mp3"));

        let err =
            generate_jingle(&transport, "https://proxy.example.com/jingle", &spec).unwrap_err();
        assert!(err.contains("invalid jingle spec"));
        // It must NOT have sent a request — validation gates the call.
        assert!(transport.seen.borrow().is_none());
    }

    #[test]
    fn generate_surfaces_an_http_error_status() {
        let spec = good_spec();
        let transport = MockTransport {
            status: 502,
            body: r#"{"error":"suno upstream unavailable"}"#.to_string(),
            seen: RefCell::new(None),
        };
        let err =
            generate_jingle(&transport, "https://proxy.example.com/jingle", &spec).unwrap_err();
        assert!(err.contains("502"), "error names the status: {err}");
    }
}
